---
- name: create home directory
  file: path={{ nfs_mount }} state=directory owner=root group=root recurse=yes
  tags:
     - nfs-dir

- name: ensure rpcbind is running
  service: name=rpcbind state=started enabled=yes
  tags:
     - rpcbind

- name: ensure {{ nfs_mount }} directory exists
  file: path={{ nfs_mount }} state=directory
  tags:
     - nfs-dir

- name: copy idmapd.conf file
  template: src=idmapd.conf.j2 dest=/etc/idmapd.conf owner=root group=root mode=0644
  notify:
     - restart rpcidmapd
     - restart ypbind
     - restart nfs
     - restart nfslock
  tags:
     - nfs-services

- name: clear keyring of all keys
  command: /usr/sbin/nfsidmap -c
  tags:
     - nfs-services

- name: configure /etc/fstab on clients
  mount: name={{ nfs_mount }} src={{ nfs_server }}:{{ nfs_path }} fstype={{ fs_type }} opts={{ nfs_opts }} state=mounted
  tags:
     - fstab-mount
